### ISSUE TITLE
Negative lookbehind not supported in Firefox

### ISSUE THREAD

**Issue by frangio** [highlightjs/highlightjs-solidity#9] opened 2019-08-18 13:23 UTC
This plugin is using negative lookbehind `(?<! ...)` which is not yet widely supported. In particular it [doesn't work in Firefox yet](https://bugzilla.mozilla.org/show_bug.cgi?id=1225665), but also not in Safari or Edge as can be seen in [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Browser_compatibility).

https://github.com/highlightjs/highlightjs-solidity/blob/3c0a75c7f075281b218f300331c18fd8fc076640/solidity.js#L133

**Comment by marcoscaceres** [comment] 2019-08-20 03:27
Ah, good point.

**Comment by miljantekic** [comment] 2019-09-18 13:42
+1 for this issue. 

I had to downgrade back to 1.0.6 because it caused our app to crash in Firefox and Safari.

**Comment by haltman-at** [comment] 2019-10-03 01:46
Oh geez, sorry, this was due to my PR.  For a fix... you could revert back to just using `\b` instead of the negative lookbehind I used?  It's not technically correct, but it'll likely be good enough most of the time?  Not sure what else to do; a complemented character set doesn't work as then the beginning gets included in the highlighting which isn't right at all.  I dunno, maybe someone else has some better idea.

**Comment by frangio** [comment] 2019-10-03 20:18
@haltman-at Can you explain why `\b` is not technically correct with an example?

**Comment by haltman-at** [comment] 2019-10-03 20:27
Sure.  The problem is that Solidity allows `$` in variable names, but JavaScript doesn't count `$` as a word character.  So, if you have a variable named, say, `value$1`, or even just `$1`, the highlighter should not highlight that `0` as a number, because it's part of a variable name.  However, if you use `\b` intead of my negative lookbehinds, it will.  Like I said, this is likely an acceptable sacrifice to make things work in browsers again, as I doubt dollar signs in variable names are used that often.

**Comment by frangio** [comment] 2019-10-03 20:43
We can transform the negative lookahead into a negative lookbehind by using negated set: `(?<=[^$])`. I would simplify the regexp by matching `(?<=[^$])\b` rather than explicitly expanding the meaning of `\b`.

**Comment by frangio** [comment] 2019-10-03 20:52
I think we should do feature detection of negative lookahead and fall back to `\b`.

**Comment by haltman-at** [comment] 2019-10-03 20:53
If that's possible in this context, that sounds like the right thing to me!

**Comment by frangio** [comment] 2019-11-21 19:36
We apparently haven't fixed this yet, because we're using RegExp literals with negative lookbehind and it fails at the parsing stage. So it seems the only alternative is to use the `RegExp` constructor with a string...

**Comment by haltman-at** [comment] 2019-12-12 01:25
OK, this should be fixed for real now!

**Closed by haltman-at** 2019-12-12 01:25 UTC
